### ISSUE TITLE
vet Fails to Run without Explicit Auth Configuration

### ISSUE THREAD

**Issue by anthonyharrison** [safedep/vet#180]
Tries to used vet to scan various lockfiles but always get the same result

`auth/verify failed due to error: ApiError: Type=invalid_request Code=api_guard_invalid_credentials Message=Authorization field missing Params=[]`

Using debug provides this additional information

`INFO[0000] Verifying auth token using Control Plane: https://api.safedep.io/control-plane/v1 `

Lockfile types tried:

requirements.txt
bom-cyclonedx
bom-spdx

Environment Linux (Debian)  running Vet version 1.5.4

**Comment by abhisek** [comment]
@anthonyharrison You need to setup `vet` to use community mode.

```
vet auth configure --community
```

Once you run this, `vet` will be configured. Alternatively, in CI/CD, you can set the environment variable `VET_COMMUNITY_MODE=1`.

**Comment by anthonyharrison** [comment]
@abhisek . I obviously missed the `vet auth` stage.  When setting this up, the requirements.txt lockfile works. Thanks. What are the limitations when using community mode?

I note that the report (to the console) is limited to only 5 packages and doesn't provide the full set of vulnerabilities which have been identified. Is there a command line option to show all of the vulnerabilities to the console?

I have tried the SPDX lockfile as well. It would appear that you only support the Json format of SPDX and not the other formats e.g. tag value is this correct? If so, this might be worth adding to the documentation as the reference provided to 

In the reported output, I get a number of instances where a 'low popularity' package is reported with a recommendation to update to the package when the package is already at the latest version! This doesn't seem correct reporting.

**Comment by abhisek** [comment]
Thanks for the feedback. This is helpful for us to improve `vet`

> What are the limitations when using community mode?

There are no limitation. `vet` depends on an API backend for fetching package metadata. We run separate cluster for community mode. We may introduce throttling in future if we are unable to handle the load, but its not a problem currently.

> Is there a command line option to show all of the vulnerabilities to the console

Yes. You can increase the count by using `--report-summary-max-advice 100` as a argument to the scan command. The default (summary) report is mean to only show the top risks without generating the noise of 1000+ risks that may be detected for very large projects. `vet` supports generate full report as JSON schema `--report-json` which contains all the information. We are also working on SARIF reporting that can be upload to Github or other vulnerability management tools.

> It would appear that you only support the Json format of SPDX and not the other formats e.g. tag value is this correct?

Yes. That is correct. Do you mind doing a PR to update the documentation?

> I get a number of instances where a 'low popularity' package is reported with a recommendation to update to the package when the package is already at the latest version! This doesn't seem correct reporting.

You are right. I should be able to release a fix for this later today.
https://github.com/safedep/vet/pull/182

**Comment by abhisek** [comment]
Closing this issue since we resolved the primary problem.
