### ISSUE TITLE
Unable to generate output through Vet

### ISSUE THREAD

**Issue by kunwaratulhax0r** [safedep/vet#200]
Hi while running Vet locally, I am not able to generate the output. While following the documentation, already `vet auth configure --community` is set. Please refer below screenshot.

![image](https://github.com/safedep/vet/assets/30471728/29c2f458-764c-4c7b-a920-869a3db90e75)

Also tried to run it with this command `vet scan --lockfiles build.gradle --lockfile-as gradle.lockfile`, results are same.
![image](https://github.com/safedep/vet/assets/30471728/b3c86faa-21e0-4748-8d45-65a5c95ce5c1)

We ran the same commands on different repos and no output received.

**Comment by abhisek** [comment]
Hi @kunwaratulhax0r Thanks for using `vet` and raising potential bugs.

`build.gradle` is not a valid lockfile actually, it is for declaring dependencies only. But `gradle.lockfile` is a valid lockfile. Can you check if you have a `gradle.lockfile` available in your source code? You should be scanning that `gradle.lockfile`. In case you do not have a `gradle.lockfile`, you should be able to generate it using `gradle`.

You can try out the Java example here which has a `build.gradle` and `gradle.lockfile` generated from `build.gradle` file
https://github.com/safedep/demo-client-java/

**Comment by kunwaratulhax0r** [comment]
So it is mandatory to have a `gradle.lockfile` in repo? Or we can run it without it? Like just by defining the path of the repo and `vet scan -D /filepath/`

**Comment by abhisek** [comment]
@kunwaratulhax0r When you are scanning a directory using `-D /path/`, `vet` actually looks for supported lockfiles such as `gradle.lockfile`, `package-lock.json` etc. Without a lockfile, `vet` cannot discover 3rd party dependencies (although we have a planned feature of discovering this from code).

For now, I suggest you add the following in your `build.gradle` file

```
dependencyLocking {
    lockAllConfigurations()
}
```

Then generate the `gradle.lockfile`

```
./gradlew assemble --write-locks
```

Then you can scan the `gradle.lockfile` using `vet`

**Comment by kunwaratulhax0r** [comment]
Yeah trying same. Thanks for the help :)

Will let you know once it's done.

**Comment by kunwaratulhax0r** [comment]
Able to produce the outout now.

Thanks for the help @abhisek, let's meet at Blackhat Asia.

**Comment by abhisek** [comment]
Great. Looking forward 👍
