### ISSUE TITLE
Generate API Key functionality is breaking

### ISSUE THREAD

**Issue by anuragpathak2608** [safedep/vet#207]
Getting error shown in the image below
<img width="1175" alt="image" src="https://github.com/safedep/vet/assets/48289570/4a154cda-57cd-4fe4-8a78-21fa86a0ed17">

**Comment by abhisek** [comment]
Thanks for reporting the issue.

Please update to latest version of vet. It does not require registration
and can use community endpoint by default.

If you are already using the latest version, you can go ahead and use it
without registration or API key.

Let me know if this works for you

**Comment by abhisek** [comment]
@anuragpathak2608 Did the solution work for you? If so, please close the issue.

**Comment by anuragpathak2608** [comment]
Hi @abhisek,

Yes, using the latest version of Vet, saw the registration steps somewhere in the documentation, hence tried It to make sure I'm getting the correct vulnerability data as I'll be comparing results with other open-source tools.

Can you confirm the source of Vuln DB?
