### ISSUE TITLE
Broken Link in README.md

### ISSUE THREAD

**Issue by AmalChandru** [safedep/vet#287]
The README.md file has a broken link in the example usage section of the vet tool (line 215). The current link points to:  https://docs.safedep.io/advanced/polic-as-code which is broken. A more appropriate link would be: https://docs.safedep.io/category/-vet-usage

If this change works, I can submit a pull request (PR) to update it.

![image](https://github.com/user-attachments/assets/1b9ce198-eb18-4826-83af-b4ca6f94c05f)

**Comment by abhisek** [comment]
@AmalChandru Thanks for reporting this. Seems like a typo. Can you raise a PR to fix this? Correct link should be

https://docs.safedep.io/advanced/policy-as-code

**Comment by AmalChandru** [comment]
Raised it [here](https://github.com/safedep/vet/pull/288)
