### ISSUE TITLE
Broken Link in Code Analysis Documentation

### ISSUE THREAD

**Issue by AmalChandru** [safedep/vet#290]
The link to `tree-sitter` in the code analysis documentation is currently broken (fig; line no: 14). While reviewing the code, it was observed that vet actually uses the `github.com/smacker/go-tree-sitter` package to build the CST and generate the graph database.

**Query for Resolution:**

1. Was this  link placement intentional (left as a placeholder for later update)?
2. Should the URL be updated to specifically point to https://github.com/smacker/go-tree-sitter, the parser currently used in the project?
3. Alternatively, since the framework utilizes tree-sitter parsers in general, should we link to the official generic documentation at https://tree-sitter.github.io/tree-sitter/ instead?

![image](https://github.com/user-attachments/assets/32c20147-a547-4d5d-9c1f-1d61144ef1a2)

**Comment by abhisek** [comment]
Thanks for the report @AmalChandru 

It is a placeholder. Feel free to raise a PR to fix the link to Tree Sitter project URL

**Comment by AmalChandru** [comment]
[Done](https://github.com/safedep/vet/pull/291/commits)

**Comment by abhisek** [comment]
Merged. Thanks @AmalChandru for your contribution.
