### ISSUE TITLE
Configurable ignoreable directory

### ISSUE THREAD

**Issue by Hritik14** [safedep/vet#40]
Currently ignorable directories are hard coded, it be nice if they were either 
* exported to a yaml file, so that anyone can add to it and compile and run
* Or extendable via command line

For eg: It considers ``node_modules`` but does not yet consider python venv. It considers dir for ``git`` but not for ``svn``

**Comment by abhisek** [comment]
@Hritik14 I just merged a change implementing this into `main` branch. I will draft a release sometime next week along with a couple of more fixes that I have in pipeline.

You can try out by installing `vet` from `main` branch `go install github.com/safedep/vet@latest` or by using the container image.
