### ISSUE TITLE
Show Ecosystem Name in Summary Report

### ISSUE THREAD

**Issue by abhisek** [safedep/vet#54]
The summary reporter presents a table of packages that are recommended for upgrade. It does not show the ecosystem of the package and only shows the name and version. While this is fine for a scan where only a single lockfile was scanned, this is a problem where multiple lockfiles were scanned with different ecosystem

![Screenshot-2023-04-09-170817](https://user-images.githubusercontent.com/31844/230770338-f1467712-bd2e-41ec-bced-2e0f633f2d2d.png)

To start improving the UX, we should start by showing the Ecosystem name in the report report table.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue.

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue.
