### ISSUE TITLE
Fix Linter Issues and Enable `golint` Guard Rail

### ISSUE THREAD

**Issue by abhisek** [safedep/vet#55]
We currently have quite a few linter issues.go

```
✗ golint ./...  | wc -l
124
```

We need to fix them and introduce a linter guard rail in 
https://github.com/safedep/vet/blob/main/.github/workflows/ci.yml

The guard rail can be as simple as integrating
https://github.com/golangci/golangci-lint-action

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue.
