### ISSUE TITLE
Incorrect Update Recommendation

### ISSUE THREAD

**Issue by anantshri** [safedep/vet#89]
running vet on gohugo repository gives odd recommendations

<img width="676" alt="image" src="https://github.com/safedep/vet/assets/236843/e51553aa-12f8-4341-9043-a11cbbe1b4eb">

felt like it wants to say the libs are low popularity but then its showing update to a version which already exists in repo the view is not very clear. even the markdown format is doing the same 

<img width="676" alt="image" src="https://github.com/safedep/vet/assets/236843/b9538e21-11af-4d9d-840a-dc0ba5f03daa">

also low popularity, drift kind of flags are missing in the md file.

**Comment by abhisek** [comment]
@anantshri This issue has been fixed in #182
